# Generated by Django 5.0.6 on 2024-07-30 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('passport_number', models.CharField(blank=True, help_text='АА0000000', max_length=9, null=True, unique=True, verbose_name='Номер паспорта')),
                ('birth_date', models.DateField(help_text='ДД.ММ.ГГГГ', verbose_name='Дата рождения')),
                ('residential_address', models.CharField(blank=True, help_text='населенный пункт, улица, дом, квартира', max_length=500, null=True, verbose_name='Адрес проживания')),
                ('is_agreed', models.BooleanField(default=False, verbose_name='Пользователь подписал соглашение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль читателя',
            },
        ),
    ]
