# Generated by Django 5.0.6 on 2024-10-13 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль читателя', 'verbose_name_plural': 'Профиль читателей'},
        ),
    ]
