# Generated by Django 5.0.6 on 2024-10-13 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_book_options_alter_bookinstance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='book',
            name='reader_count',
        ),
    ]
