# Generated by Django 5.0.6 on 2024-10-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_book_rating_remove_book_reader_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('available', 'доступна для выдачи'), ('not_available', 'НЕ доступна для выдачи'), ('in_cart', 'в корзине')], default='available', max_length=13, verbose_name='Статус'),
        ),
    ]
