# Generated by Django 5.0.6 on 2024-10-13 21:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_remove_book_rating_remove_book_reader_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата возврата')),
                ('reader_assessment', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, null=True, verbose_name='Оценка')),
                ('damage_description', models.TextField(blank=True, null=True, verbose_name='Описание повреждений')),
                ('book_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bookinstance', verbose_name='Экземпляр книги')),
            ],
            options={
                'verbose_name': 'Возврат',
                'verbose_name_plural': 'Возвраты',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.bookinstance', verbose_name='Экземпляр книги')),
            ],
        ),
        migrations.CreateModel(
            name='DamagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='book_damages/', verbose_name='Повреждения книги')),
                ('book_damage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.bookreturn', verbose_name='Поврежедния')),
            ],
            options={
                'verbose_name': 'Фотография повреждения',
                'verbose_name_plural': 'Фотографии повреждений',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('return_date', models.DateField(verbose_name='Дата возврата')),
                ('reader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-issue_date',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.bookinstance', verbose_name='Экземпляр книги')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
            ],
        ),
    ]
