# Generated by Django 5.0.6 on 2024-10-25 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagephoto',
            name='book_damage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.bookreturn', verbose_name='Поврежедния'),
        ),
    ]
